name: NextJS Pipeline #workflow name
on:
  push:
    branches:
      - master #execute the below jobs in any push (commit) in the master branch
jobs:
  job1:
    name: My name is job1
    runs-on: ubuntu-latest
    steps: #steps array anything within start with -
      - name: First setp - job1
        run: echo "First Setp in job1"
      - name: Create a File
        run: touch test.txt  
  job2: 
    name: My name is job2  
    runs-on: ubuntu-latest
    steps:
      - name: Verify the File - Job 2
        run: ls -l